name: One-off Cleanup (remove Ikyu traces)

on:
  workflow_dispatch: {}   # 手動実行のみ

env:
  TZ: Asia/Tokyo

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run cleanup script
        run: |
          python scripts/cleanup_remove_ikyu.py

      - name: Commit & Push changes (auto-rebase)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          n=0
          until [ $n -ge 5 ]; do
            git commit -m "chore: purge Ikyu traces from master/meta [skip ci]" && \
            git pull --rebase && \
            git push && exit 0
            n=$((n+1))
            echo "Retrying push ($n/5) ..."
            sleep 3
          done
          echo "Failed to push after retries." >&2
          exit 1
