name: Daily Dummy JSON

on:
  schedule:
    - cron: '0 23 * * *'   # JST 08:00（UTC23:00）に実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create dummy JSON
        run: |
          mkdir -p data
          echo '{
            "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "message": "これはダミーデータです。OTAブリッジ経路テスト用。"
          }' > data/dummy.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/dummy.json
          git commit -m "update dummy.json [skip ci]" || echo "No changes"
          git push
