name: Fetch Rakuten Min Prices

on:
  schedule:
    - cron: "0 0 * * *"   # 毎日 09:00 JST（= 00:00 UTC）
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: rakuten-data-writer-main
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -V
          if [ -f requirements.txt ]; then
           pip install -r requirements.txt
          else
           echo "requirements.txt not found. Installing minimal runtime deps..."
           pip install "requests>=2.31.0" "python-dateutil>=2.9.0" "pandas>=2.2.2" "openpyxl>=3.1.2"
          fi


      - name: Run fetch_rakuten_min_prices.py
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
        run: |
          python fetch_rakuten_min_prices.py

      - name: Commit & Push JSON (auto-rebase with retry)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"

          # 変更があればステージング
          git add data/competitor_min_prices.json data/last_updated.json || true

          # 差分が無ければ終了
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "update competitor_min_prices.json (rakuten min prices) [skip ci]"

          # 先行コミットがあっても自分のコミットを載せ替えてから push（最大5回リトライ）
          pushed=0
          for i in 1 2 3 4 5; do
            git pull --rebase origin "${GITHUB_REF_NAME:-main}" || (git rebase --abort && sleep 3)
            if git push origin HEAD:"${GITHUB_REF_NAME:-main}"; then
              pushed=1
              break
            fi
            echo "Push failed. retry in $((i*5))s..."
            sleep $((i*5))
          done
          test "$pushed" -eq 1
