name: Fetch Rakuten Min Prices

permissions:
  contents: write

on:
  schedule:
    # JST 08:50（= UTC 23:50）に毎日実行（口コミと数分ずらす）
    - cron: '50 23 * * *'
  workflow_dispatch:

concurrency:
  group: fetch-min-prices
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_rakuten_min_prices.py
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
        run: |
          python fetch_rakuten_min_prices.py

      - name: Commit & Push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/competitor_min_prices.json
          git commit -m "update competitor_min_prices.json (rakuten min prices) [skip ci]" || echo "No changes"
          git push
